Output integration test status in github action pipeline

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -24,3 +24,12 @@ jobs:
       - name: Run API Integration Tests
         run: |
           make integration
+          integration_test_status=$?
+
+          if [ $integration_test_status -eq 0 ]; then
+            echo "✅ Integration Tests Pass"
+            exit 0
+          else
+            echo "🚨 Integration Test Failure"
+            exit 1
+          fi
